"""Reproduce synthetic inventories; no real host or credential inputs are accepted."""
import argparse
import hashlib
import json
from pathlib import Path

RECIPE = 'box-binder-synthetic-v1'
ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / 'skills/box-rclone-binder/tests/fixtures/inventories.json'


def inventory(mode='jwt', count=2):
    hosts = [{'host': 'node%d.example.com' % (i + 1), 'remote_name': 'box',
              'auth_mode': mode, 'config_dir': '/etc/box-binder', 'root_folder_id': '0'}
             for i in range(count)]
    if mode == 'oauth-broker':
        for i, host in enumerate(hosts):
            host['broker_role'] = 'master' if i == 0 else 'slave'
    return {'version': 1, 'hosts': hosts, 'secrets': {'source': 'env',
            'jwt_config_ref': 'BOX_TEST_JWT', 'client_id_ref': 'BOX_TEST_ID',
            'client_secret_ref': 'BOX_TEST_SECRET', 'box_subject_id_ref': 'BOX_TEST_SUBJECT',
            'broker_state_ref': 'BOX_TEST_STATE'}}


def canary():
    return 'SYNTHETIC_' + hashlib.sha256(RECIPE.encode()).hexdigest()[:24]


def runtime_receipt(host, action, operation_id, case='matching'):
    """Build a complete synthetic runtime response, with explicit malformed variants."""
    result = {'ok': True, 'host': host['host'], 'auth_mode': host.get('auth_mode', 'jwt'),
              'action': action, 'operation_id': operation_id}
    if case == 'missing':
        result.pop('host')
    elif case == 'other':
        result['host'] = 'other-node.example.com'
    elif case == 'empty':
        result['host'] = ''
    elif case == 'non-string':
        result['host'] = 1
    elif case == 'unsuccessful':
        result['ok'] = False
    elif case == 'stale':
        result['operation_id'] = 'synthetic-old-operation'
    elif case == 'wrong-action':
        result['action'] = 'refresh' if action != 'refresh' else 'validate'
    elif case == 'wrong-mode':
        result['auth_mode'] = 'jwt' if result['auth_mode'] != 'jwt' else 'ccg-native'
    elif case != 'matching':
        raise ValueError('unknown synthetic receipt case')
    return result


def invalid_host_identity(case):
    host = inventory()['hosts'][0]
    if case == 'missing':
        host.pop('host')
    else:
        host['host'] = {'empty': '', 'whitespace': ' ', 'non-string': 1,
                        'nul': 'node\x00.example.com'}[case]
    return host


def access_token():
    return {'access_token': canary(), 'expiry': '2099-01-01T00:00:00Z', 'token_type': 'bearer'}


def receipt_test_source():
    return '''"""Generated by tools/make_fixtures.py; all host and token data are synthetic."""
import json
from pathlib import Path
import sys
from types import SimpleNamespace

import pytest

ROOT = Path(__file__).resolve().parents[3]
sys.path[:0] = [str(ROOT / 'tools'), str(ROOT / 'skills/box-rclone-binder/scripts')]
from make_fixtures import access_token, invalid_host_identity, inventory, runtime_receipt
import box_binder as cli
from boxbinder import config, refresh, runtime
from boxbinder.drivers import FakeHostDriver, RemoteError


def response(host, case='matching'):
    def receive(argv, input_text):
        operation_id = argv[argv.index('--operation-id') + 1]
        return 0, json.dumps(runtime_receipt(host, argv[2], operation_id, case)), ''
    return receive


@pytest.mark.parametrize('mode', ['jwt', 'ccg-native', 'ccg-mint', 'oauth-broker'])
@pytest.mark.parametrize('case', ['matching', 'missing', 'other', 'empty', 'non-string'])
def test_invocation_binds_receipt_to_selected_host(mode, case):
    host = inventory(mode, 1)['hosts'][0]
    driver = FakeHostDriver(host, responses={'python3': response(host, case)})
    if case == 'matching':
        report = refresh.invoke_runtime(driver, host, 'validate')
        assert report['ok'] is True and report['host'] == host['host']
    else:
        with pytest.raises(RemoteError):
            refresh.invoke_runtime(driver, host, 'validate')


@pytest.mark.parametrize('case', ['unsuccessful', 'stale', 'wrong-action', 'wrong-mode'])
def test_host_match_does_not_replace_existing_receipt_guards(case):
    host = inventory()['hosts'][0]
    driver = FakeHostDriver(host, responses={'python3': response(host, case)})
    with pytest.raises(RemoteError):
        refresh.invoke_runtime(driver, host, 'validate')


@pytest.mark.parametrize('mode', ['jwt', 'ccg-native', 'ccg-mint'])
@pytest.mark.parametrize('case', ['missing', 'other'])
def test_refresh_identity_failure_preserves_other_host_success(mode, case):
    cfg = config.Config(inventory(mode))
    first, second = cfg.hosts
    drivers = {first['host']: FakeHostDriver(first, responses={'python3': response(first)}),
               second['host']: FakeHostDriver(second, responses={'python3': response(second, case)})}
    args = SimpleNamespace(host=[], dry_run=False, timeout=20)
    code, report = cli.cmd_refresh(cfg, args, factory=lambda host, **kwargs: drivers[host['host']])
    assert code == cli.EXIT_PARTIAL and report['status'] == 'partial'
    assert report['summary'] == {'total': 2, 'failed': 1, 'succeeded': 1}
    assert [(row['host'], row['ok']) for row in report['results']] == [
        (first['host'], True), (second['host'], False)]


def test_broker_peer_identity_failure_preserves_successful_peer(monkeypatch):
    master, first, second = inventory('oauth-broker', 3)['hosts']
    token = access_token()
    def read(path):
        return {'hosts': [first, second]} if Path(path).name == 'peers.json' else token
    monkeypatch.setattr(runtime, 'read_private_json', read)
    monkeypatch.setattr(runtime, 'execute', lambda *args, **kwargs: None)
    drivers = {first['host']: FakeHostDriver(first, responses={'python3': response(first)}),
               second['host']: FakeHostDriver(second, responses={'python3': response(second, 'other')})}
    report = runtime.broker_cycle(master, factory=lambda host, **kwargs: drivers[host['host']])
    assert report['ok'] is False
    assert [(row['host'], row['ok']) for row in report['results']] == [
        (first['host'], True), (second['host'], False)]


@pytest.mark.parametrize('mode', ['jwt', 'ccg-native', 'ccg-mint', 'oauth-broker'])
def test_runtime_report_identifies_the_executed_host(mode, monkeypatch, capsys):
    host = inventory(mode, 1)['hosts'][0]
    monkeypatch.setattr(runtime, 'read_private_json', lambda path: host)
    monkeypatch.setattr(runtime, 'validate_access', lambda *args, **kwargs: None)
    assert runtime.main(['validate', '--host-file', 'synthetic-host.json',
                         '--operation-id', 'synthetic-current-operation']) == 0
    report = json.loads(capsys.readouterr().out)
    assert report['ok'] is True and report.get('host') == host['host']
    assert report['auth_mode'] == mode and report['action'] == 'validate'
    assert report['operation_id'] == 'synthetic-current-operation'


@pytest.mark.parametrize('case', ['missing', 'empty', 'whitespace', 'non-string', 'nul'])
def test_runtime_rejects_invalid_host_before_external_execution(case, monkeypatch, capsys):
    host = invalid_host_identity(case)
    calls = []
    monkeypatch.setattr(runtime, 'read_private_json', lambda path: host)
    monkeypatch.setattr(runtime, 'validate_access', lambda *args, **kwargs: calls.append(True))
    assert runtime.main(['validate', '--host-file', 'synthetic-host.json']) == 1
    report = json.loads(capsys.readouterr().out)
    assert report['ok'] is False and calls == []
'''


def config_discovery_test_source():
    return '''"""Generated config-discovery regressions; inventories and paths are synthetic."""
import importlib.util
import json
from pathlib import Path
import sys
from types import SimpleNamespace

import pytest

ROOT = Path(__file__).resolve().parents[3]
sys.path[:0] = [str(ROOT / 'tools'), str(ROOT / 'skills/box-rclone-binder/scripts')]
from make_fixtures import inventory
import box_binder as cli
import init_config as initializer
import verify_config as verifier
from boxbinder.config import ConfigError


@pytest.fixture
def isolated_paths(tmp_path, monkeypatch):
    home = tmp_path / 'home'
    cwd = tmp_path / 'work'
    home.mkdir()
    cwd.mkdir()
    monkeypatch.setenv('HOME', str(home))
    monkeypatch.setenv('USERPROFILE', str(home))
    monkeypatch.delenv(cli.CONFIG_ENV, raising=False)
    monkeypatch.delenv(cli.CONFIG_ENV_DIR, raising=False)
    monkeypatch.chdir(cwd)
    return home, cwd


@pytest.mark.parametrize('legacy', ['cwd', 'dotdir', 'xdg'])
@pytest.mark.parametrize('configured', [False, True])
def test_missing_companion_never_selects_legacy_inventory(
        legacy, configured, isolated_paths, tmp_path, monkeypatch):
    home, cwd = isolated_paths
    locations = {'cwd': cwd / 'machines.yaml',
                 'dotdir': home / '.box-rclone-binder-config/machines.yaml',
                 'xdg': home / '.config/box-rclone-binder/machines.yaml'}
    path = locations[legacy]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(inventory()), encoding='utf-8')
    companion = str(tmp_path / 'private-companion/machines.yaml') if configured else None
    monkeypatch.setattr(cli, '_companion_config_path', lambda: companion)
    if configured:
        assert cli.discover_config_path() == companion
    else:
        with pytest.raises(ConfigError):
            cli.discover_config_path()


def test_explicit_and_environment_priority_is_preserved(isolated_paths, tmp_path, monkeypatch):
    explicit = tmp_path / 'explicit.yaml'
    env_file = tmp_path / 'environment.yaml'
    env_dir = tmp_path / 'environment-dir'
    env_dir.mkdir()
    monkeypatch.setattr(cli, '_companion_config_path', lambda: None)
    monkeypatch.setenv(cli.CONFIG_ENV, str(env_file))
    monkeypatch.setenv(cli.CONFIG_ENV_DIR, str(env_dir))
    assert cli.discover_config_path(str(explicit)) == str(explicit)
    assert cli.discover_config_path() == str(env_file)
    monkeypatch.delenv(cli.CONFIG_ENV)
    assert cli.discover_config_path() == str(env_dir / 'machines.yaml')


@pytest.mark.parametrize('fault', ['no-spec', 'no-loader', 'no-api', 'bad-api', 'load-error'])
def test_broken_resolver_is_a_config_error(fault, isolated_paths, monkeypatch):
    def execute(module):
        if fault == 'load-error':
            raise ImportError('synthetic resolver dependency missing')
    spec = None if fault == 'no-spec' else SimpleNamespace(
        loader=None if fault == 'no-loader' else SimpleNamespace(exec_module=execute))
    module = SimpleNamespace()
    if fault == 'bad-api':
        module.resolve_companion_root = 1
    monkeypatch.setattr(importlib.util, 'spec_from_file_location', lambda *args: spec)
    monkeypatch.setattr(importlib.util, 'module_from_spec', lambda value: module)
    with pytest.raises(ConfigError):
        cli._companion_config_path()


@pytest.mark.parametrize('entrypoint', ['cli', 'verify', 'init'])
def test_uninitialized_entrypoints_fail_without_creating_config(
        entrypoint, isolated_paths, monkeypatch, capsys):
    home, cwd = isolated_paths
    monkeypatch.setattr(cli, '_companion_config_path', lambda: None)
    if entrypoint == 'cli':
        code = cli.run(['verify-config', '--json'])
    elif entrypoint == 'verify':
        code = verifier.main(['--json'])
    else:
        monkeypatch.setattr(sys, 'argv', ['init_config.py'])
        code = initializer.main()
    assert code == 3
    assert not list(home.rglob('machines.yaml'))
    assert not (cwd / 'machines.yaml').exists()
    if entrypoint != 'init':
        report = json.loads(capsys.readouterr().out)
        assert report['exit_code'] == 3 and report['error']


@pytest.mark.parametrize('selected_by', ['companion', 'environment'])
def test_init_and_verify_use_the_same_default_inventory(
        selected_by, isolated_paths, tmp_path, monkeypatch, capsys):
    expected = tmp_path / 'private-companion/machines.yaml'
    monkeypatch.setattr(cli, '_companion_config_path', lambda: str(expected))
    if selected_by == 'environment':
        expected = tmp_path / 'selected-companion/machines.yaml'
        monkeypatch.setenv(cli.CONFIG_ENV, str(expected))
    monkeypatch.setattr(sys, 'argv', ['init_config.py'])
    assert initializer.main() == 0
    assert expected.is_file()
    assert expected.read_bytes() == Path(initializer.template_path()).read_bytes()
    assert cli.discover_config_path() == str(expected)
    capsys.readouterr()
    assert verifier.main(['--json']) == 0
    assert json.loads(capsys.readouterr().out)['config_path'] == str(expected)


def test_explicit_init_preserves_existing_file_without_force(
        isolated_paths, tmp_path, monkeypatch):
    target = tmp_path / 'selected-companion/machines.yaml'
    target.parent.mkdir()
    previous = json.dumps(inventory('ccg-native', 1)).encode('utf-8')
    target.write_bytes(previous)
    monkeypatch.setattr(sys, 'argv', ['init_config.py', '--out', str(target)])
    assert initializer.main() == 0
    assert target.read_bytes() == previous
    monkeypatch.setattr(sys, 'argv', ['init_config.py', '--out', str(target), '--force'])
    assert initializer.main() == 0
    assert target.read_bytes() == Path(initializer.template_path()).read_bytes()


@pytest.mark.parametrize('relative_target', ['machines.yaml', 'config/machines.yaml'])
def test_init_refuses_inventory_inside_the_public_tool_tree(
        relative_target, isolated_paths, tmp_path, monkeypatch):
    tool = tmp_path / 'synthetic-public-tool'
    entrypoint = tool / 'skills/box-rclone-binder/scripts/init_config.py'
    entrypoint.parent.mkdir(parents=True)
    target = tool / relative_target
    template = initializer.template_path()
    monkeypatch.setattr(initializer, '__file__', str(entrypoint))
    monkeypatch.setattr(initializer, 'template_path', lambda: template)
    monkeypatch.setattr(sys, 'argv', ['init_config.py', '--out', str(target)])
    assert initializer.main() == 3
    assert not target.exists()


def test_environment_hot_swap_changes_verified_inventory(
        isolated_paths, tmp_path, monkeypatch, capsys):
    for count in (1, 2):
        path = tmp_path / ('fleet%d.yaml' % count)
        path.write_text(json.dumps(inventory(count=count)), encoding='utf-8')
        monkeypatch.setenv(cli.CONFIG_ENV, str(path))
        assert verifier.main(['--json']) == 0
        result = json.loads(capsys.readouterr().out)
        assert result['ready'] is True and len(result['hosts']) == count
        assert result['config_path'] == str(path)
'''


def config_example_sources():
    return {
        'machines.example.yaml': '''# Generated by tools/make_fixtures.py; synthetic inventory with no secret values.
# Inline secret values are rejected by box-binder verify-config.
version: 1

defaults:
  auth_mode: jwt              # jwt | ccg-native | ccg-mint | oauth-broker
  box_sub_type: enterprise    # enterprise | user
  remote_name: box
  root_folder_id: "0"         # Box folder URL tail; "0" = service-account root
  rclone_min_version: "1.71.0"
  config_dir: /etc/box-binder
  health_interval: "*:0/15"   # systemd OnCalendar; every 15 min
  mint_interval_min: 45       # ccg-mint only: re-mint before the 60-min expiry
  impersonate_user_id: ""     # optional: as-user (needs App + Enterprise access)

secrets:
  # Only WHERE to read from — never the value. `source` selects the resolver.
  source: env                 # env | file | op | vault | aws-ssm
  jwt_config_ref: BOX_BINDER_JWT_CONFIG       # env var / op:// path holding config.json content
  client_id_ref: BOX_BINDER_CLIENT_ID
  client_secret_ref: BOX_BINDER_CLIENT_SECRET
  box_subject_id_ref: BOX_BINDER_ENTERPRISE_ID
  rclone_config_pass_ref: BOX_BINDER_RCLONE_PASS   # only if you fall back to an encrypted conf

hosts:
  - host: 203.0.113.10
    ssh: "root@203.0.113.10"
    ssh_opts: "-o BatchMode=yes -o ConnectTimeout=12 -o StrictHostKeyChecking=accept-new"
    # optional per-host overrides: root_folder_id / auth_mode / config_dir
  # - host: <add the rest of your servers here>

alerts:
  discord: true
  relay: "~/.local/relay.py"  # a relay taking: send --stream infra --text <msg>
                              # leave unset to use $BOX_RCLONE_BINDER_RELAY, then a
                              # simple notifier at $BOX_RCLONE_BINDER_NOTIFIER
  on_recovered: INFO          # auth failed then self-healed
  on_heal_failed: CRITICAL    # self-heal failed; human needed
  on_drift: WARN              # cross-host structure drift
  jitter_sec: 30              # stagger probes/alerts to dodge 429
''',
        'secrets.env.example': '''# Generated by tools/make_fixtures.py; synthetic example only.
# Fill a chmod-600 file outside the public repository, such as /etc/box-binder/runtime.env.
# Real values belong in private storage; private versioned backups are allowed.
#
# JWT mode: provide the path to config.json (installed out-of-band, chmod 600).
#   RCLONE_CONFIG_BOX_BOX_CONFIG_FILE is already set by box-binder's secrets.env.
#
# CCG mode: inject the client credentials from your secret backend at runtime:
# BOX_BINDER_CLIENT_ID=__from_secret_backend__
# BOX_BINDER_CLIENT_SECRET=__from_secret_backend__
# BOX_BINDER_ENTERPRISE_ID=__from_secret_backend__
#
# Encrypted-conf fallback only:
# BOX_BINDER_RCLONE_PASS=__from_secret_backend__
''',
    }


def render():
    return json.dumps({'recipe': RECIPE, 'synthetic_origin': True,
                       'inventories': {mode: inventory(mode) for mode in
                                       ('jwt', 'ccg-native', 'ccg-mint', 'oauth-broker')}}, indent=2) + '\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--out', type=Path, help='Generate the fixture basename into this directory.')
    args = parser.parse_args()
    outputs = {FIXTURE: render().encode('utf-8'),
               FIXTURE.parent.parent / 'test_receipt_identity.py': receipt_test_source().encode('utf-8'),
               FIXTURE.parent.parent / 'test_config_discovery.py': config_discovery_test_source().encode('utf-8')}
    outputs.update({ROOT / 'skills/box-rclone-binder/config' / name: value.encode('utf-8')
                    for name, value in config_example_sources().items()})
    outputs = {args.out / path.name if args.out else path: value for path, value in outputs.items()}
    if args.check:
        ok = all(path.is_file() and path.read_bytes() == expected for path, expected in outputs.items())
        print('Synthetic fixtures match generator.' if ok else 'Synthetic fixtures differ.')
        return 0 if ok else 1
    for path, expected in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(expected)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
