"""Generated by tools/make_fixtures.py; synthetic source-aware file-reference controls."""

import ast
import ntpath
from pathlib import Path, PurePosixPath, PureWindowsPath
import posixpath
import re
import shlex
from types import SimpleNamespace
import unittest


ROOT = Path(__file__).resolve().parents[3]
CONFIG_PATH = ROOT / "skills/box-rclone-binder/scripts/boxbinder/config.py"


def production(path_module):
    """Load only the actual pure validation definitions, without importing the module."""
    names = {
        "ConfigError", "Config", "_is_secretish", "_validate_document",
        "_validate_parsed_secrets", "_validate_secret_refs", "_merged_secret_refs",
        "validate", "validate_config_dir", "_validate_host_fields", "validate_host",
    }
    constants = {"_SECRET_VALUE_KEYS", "_POINTER_RE", "_VALID_SOURCES"}
    selected = []
    found = set()
    for node in ast.parse(CONFIG_PATH.read_bytes(), str(CONFIG_PATH)).body:
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)) and node.name in names:
            selected.append(node)
            found.add(node.name)
        elif isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
            if isinstance(target, ast.Name) and target.id in constants:
                selected.append(node)
                found.add(target.id)
    if found != names | constants:
        raise AssertionError("production validation definition set changed")
    namespace = {
        "re": re, "posixpath": posixpath, "shlex": shlex,
        "os": SimpleNamespace(path=path_module),
        "Path": PureWindowsPath if path_module is ntpath else PurePosixPath,
        "AUTH_MODES": ("jwt", "ccg-native", "ccg-mint", "oauth-broker"),
    }
    exec(compile(ast.Module(body=selected, type_ignores=[]), str(CONFIG_PATH), "exec"),
         namespace)
    return namespace


def document(source, pointer, scope="global"):
    refs = {"jwt_config_ref": pointer}
    host = {"host": "node1.example.com", "remote_name": "box", "auth_mode": "jwt"}
    data = {"version": 1, "hosts": [host]}
    if scope == "global":
        data["secrets"] = dict(refs, source=source)
    elif scope == "host-explicit":
        host["secrets"] = dict(refs, source=source)
    elif scope == "host-inherited":
        data["secrets"] = {"source": source}
        host["secrets"] = refs
    elif scope == "defaults-explicit":
        data["defaults"] = {"secrets": dict(refs, source=source)}
    elif scope == "defaults-inherited":
        data["secrets"] = {"source": source}
        data["defaults"] = {"secrets": refs}
    else:
        raise AssertionError("unknown synthetic scope")
    return data


class Box15FileReferenceTests(unittest.TestCase):
    def validate_document(self, namespace, data):
        cfg = namespace["Config"](data)
        namespace["validate"](cfg)
        return cfg

    def test_absolute_file_references_follow_global_default_and_host_sources(self):
        paths = [
            (ntpath, "C:/synthetic-private/jwt.json"),
            (ntpath, r"C:\synthetic-private\jwt.json"),
            (ntpath, r"\\synthetic-host\synthetic-share\jwt.json"),
            (posixpath, "/synthetic-private/jwt.json"),
        ]
        for path_module, pointer in paths:
            namespace = production(path_module)
            for scope in ("global", "host-explicit", "host-inherited",
                          "defaults-explicit", "defaults-inherited"):
                with self.subTest(platform=path_module.__name__, pointer=pointer, scope=scope):
                    cfg = self.validate_document(namespace, document("file", pointer, scope))
                    refs = namespace["_merged_secret_refs"](cfg, cfg.hosts[0])
                    self.assertEqual(refs, {"source": "file", "jwt_config_ref": pointer})

    def test_file_source_rejects_relative_paths_and_other_pointer_forms(self):
        bad = [
            "synthetic-private/jwt.json", "./synthetic-private/jwt.json",
            "C:synthetic-private/jwt.json", r"\synthetic-private\jwt.json", "SYNTHETIC_JWT",
            "vault://synthetic/jwt", "synthetic literal value",
            "C:/synthetic private/jwt.json", "C:/synthetic-private/jwt.json\0",
            "/synthetic private/jwt.json", "/synthetic-private/jwt.json\0",
        ]
        for path_module in (ntpath, posixpath):
            namespace = production(path_module)
            for pointer in bad:
                with self.subTest(platform=path_module.__name__, pointer=pointer):
                    with self.assertRaises(namespace["ConfigError"]):
                        self.validate_document(namespace, document("file", pointer))
        namespace = production(posixpath)
        with self.assertRaises(namespace["ConfigError"]):
            self.validate_document(namespace, document("file", "C:/synthetic-private/jwt.json"))

    def test_other_sources_retain_pointer_contracts(self):
        valid = [
            ("env", "SYNTHETIC_JWT"), ("op", "op://synthetic/jwt"),
            ("vault", "vault://synthetic/jwt"), ("aws-ssm", "aws-ssm://synthetic/jwt"),
        ]
        for path_module, path in (
            (ntpath, "C:/synthetic-private/jwt.json"),
            (posixpath, "/synthetic-private/jwt.json"),
        ):
            namespace = production(path_module)
            for source, pointer in valid:
                with self.subTest(platform=path_module.__name__, source=source):
                    self.validate_document(namespace, document(source, pointer))
                    with self.assertRaises(namespace["ConfigError"]):
                        self.validate_document(namespace, document(source, path))
                    wrong_uri = "op://synthetic/jwt" if source != "op" else "vault://synthetic/jwt"
                    with self.assertRaises(namespace["ConfigError"]):
                        self.validate_document(namespace, document(source, wrong_uri))

    def test_host_source_overrides_are_checked_after_merging(self):
        namespace = production(ntpath)
        data = document("file", "C:/synthetic-private/jwt.json")
        data["hosts"][0]["secrets"] = {"source": "env", "jwt_config_ref": "SYNTHETIC_JWT"}
        cfg = self.validate_document(namespace, data)
        self.assertEqual(namespace["_merged_secret_refs"](cfg, cfg.hosts[0]),
                         {"source": "env", "jwt_config_ref": "SYNTHETIC_JWT"})
        data["hosts"][0]["secrets"] = {"source": "env"}
        with self.assertRaises(namespace["ConfigError"]):
            self.validate_document(namespace, data)
        data = document("env", "SYNTHETIC_JWT")
        data["hosts"][0]["secrets"] = {
            "source": "file", "jwt_config_ref": "C:/synthetic-private/jwt.json",
        }
        self.validate_document(namespace, data)

    def test_literal_fields_and_nonstring_references_remain_forbidden(self):
        namespace = production(ntpath)
        for value in (123, [], {}, "synthetic-secret-literal"):
            with self.subTest(value=value):
                with self.assertRaises(namespace["ConfigError"]):
                    self.validate_document(namespace, document("file", value))
        data = document("file", "C:/synthetic-private/jwt.json")
        data["secrets"]["client_secret"] = "synthetic-secret-literal"
        with self.assertRaises(namespace["ConfigError"]):
            self.validate_document(namespace, data)
