"""Generated by tools/make_fixtures.py; all host and token data are synthetic."""
import json
from pathlib import Path
import sys
from types import SimpleNamespace

import pytest

ROOT = Path(__file__).resolve().parents[3]
sys.path[:0] = [str(ROOT / 'tools'), str(ROOT / 'skills/box-rclone-binder/scripts')]
from make_fixtures import access_token, invalid_host_identity, inventory, runtime_receipt
import box_binder as cli
from boxbinder import config, refresh, runtime
from boxbinder.drivers import FakeHostDriver, RemoteError


def response(host, case='matching'):
    def receive(argv, input_text):
        operation_id = argv[argv.index('--operation-id') + 1]
        return 0, json.dumps(runtime_receipt(host, argv[2], operation_id, case)), ''
    return receive


@pytest.mark.parametrize('mode', ['jwt', 'ccg-native', 'ccg-mint', 'oauth-broker'])
@pytest.mark.parametrize('case', ['matching', 'missing', 'other', 'empty', 'non-string'])
def test_invocation_binds_receipt_to_selected_host(mode, case):
    host = inventory(mode, 1)['hosts'][0]
    driver = FakeHostDriver(host, responses={'python3': response(host, case)})
    if case == 'matching':
        report = refresh.invoke_runtime(driver, host, 'validate')
        assert report['ok'] is True and report['host'] == host['host']
    else:
        with pytest.raises(RemoteError):
            refresh.invoke_runtime(driver, host, 'validate')


@pytest.mark.parametrize('case', ['unsuccessful', 'stale', 'wrong-action', 'wrong-mode'])
def test_host_match_does_not_replace_existing_receipt_guards(case):
    host = inventory()['hosts'][0]
    driver = FakeHostDriver(host, responses={'python3': response(host, case)})
    with pytest.raises(RemoteError):
        refresh.invoke_runtime(driver, host, 'validate')


@pytest.mark.parametrize('mode', ['jwt', 'ccg-native', 'ccg-mint'])
@pytest.mark.parametrize('case', ['missing', 'other'])
def test_refresh_identity_failure_preserves_other_host_success(mode, case):
    cfg = config.Config(inventory(mode))
    first, second = cfg.hosts
    drivers = {first['host']: FakeHostDriver(first, responses={'python3': response(first)}),
               second['host']: FakeHostDriver(second, responses={'python3': response(second, case)})}
    args = SimpleNamespace(host=[], dry_run=False, timeout=20)
    code, report = cli.cmd_refresh(cfg, args, factory=lambda host, **kwargs: drivers[host['host']])
    assert code == cli.EXIT_PARTIAL and report['status'] == 'partial'
    assert report['summary'] == {'total': 2, 'failed': 1, 'succeeded': 1}
    assert [(row['host'], row['ok']) for row in report['results']] == [
        (first['host'], True), (second['host'], False)]


def test_broker_peer_identity_failure_preserves_successful_peer(monkeypatch):
    master, first, second = inventory('oauth-broker', 3)['hosts']
    token = access_token()
    def read(path):
        return {'hosts': [first, second]} if Path(path).name == 'peers.json' else token
    monkeypatch.setattr(runtime, 'read_private_json', read)
    monkeypatch.setattr(runtime, 'execute', lambda *args, **kwargs: None)
    drivers = {first['host']: FakeHostDriver(first, responses={'python3': response(first)}),
               second['host']: FakeHostDriver(second, responses={'python3': response(second, 'other')})}
    report = runtime.broker_cycle(master, factory=lambda host, **kwargs: drivers[host['host']])
    assert report['ok'] is False
    assert [(row['host'], row['ok']) for row in report['results']] == [
        (first['host'], True), (second['host'], False)]


@pytest.mark.parametrize('mode', ['jwt', 'ccg-native', 'ccg-mint', 'oauth-broker'])
def test_runtime_report_identifies_the_executed_host(mode, monkeypatch, capsys):
    host = inventory(mode, 1)['hosts'][0]
    monkeypatch.setattr(runtime, 'read_private_json', lambda path: host)
    monkeypatch.setattr(runtime, 'validate_access', lambda *args, **kwargs: None)
    assert runtime.main(['validate', '--host-file', 'synthetic-host.json',
                         '--operation-id', 'synthetic-current-operation']) == 0
    report = json.loads(capsys.readouterr().out)
    assert report['ok'] is True and report.get('host') == host['host']
    assert report['auth_mode'] == mode and report['action'] == 'validate'
    assert report['operation_id'] == 'synthetic-current-operation'


@pytest.mark.parametrize('case', ['missing', 'empty', 'whitespace', 'non-string', 'nul'])
def test_runtime_rejects_invalid_host_before_external_execution(case, monkeypatch, capsys):
    host = invalid_host_identity(case)
    calls = []
    monkeypatch.setattr(runtime, 'read_private_json', lambda path: host)
    monkeypatch.setattr(runtime, 'validate_access', lambda *args, **kwargs: calls.append(True))
    assert runtime.main(['validate', '--host-file', 'synthetic-host.json']) == 1
    report = json.loads(capsys.readouterr().out)
    assert report['ok'] is False and calls == []
