"""Generated by tools/make_fixtures.py; Box4 controls use synthetic values and inert boundaries."""
import ast
import builtins
import copy
import errno
import hashlib
import importlib.machinery
import io
import json
import os
from pathlib import Path
import posixpath
import re
import shlex
import subprocess
import sys
from types import SimpleNamespace
import unittest

ROOT = Path(__file__).resolve().parents[3]
SCRIPTS = ROOT / "skills/box-rclone-binder/scripts"


def source(relative):
    return (ROOT / relative).read_bytes()


def definitions(relative, names, namespace):
    tree = ast.parse(source(relative), str(ROOT / relative))
    selected = [node for node in tree.body
                if isinstance(node, (ast.FunctionDef, ast.ClassDef)) and node.name in names]
    if len(selected) != len(names):
        raise AssertionError("Definition set changed")
    exec(compile(ast.Module(body=selected, type_ignores=[]), str(ROOT / relative), "exec"), namespace)
    return namespace


def fixtures():
    namespace = {"__name__": "box4_generator", "__file__": str(ROOT / "tools/make_fixtures.py")}
    exec(compile(source("tools/make_fixtures.py"), namespace["__file__"], "exec"), namespace)
    return namespace["box4_cases"]()


class Box4AuthorTests(unittest.TestCase):
    def setUp(self):
        self.case = fixtures()

    def alerts(self, returncode=0):
        namespace = {"__name__": "box4_alerts"}
        path = ROOT / "skills/box-rclone-binder/scripts/boxbinder/alerts.py"
        exec(compile(path.read_bytes(), str(path), "exec"), namespace)
        calls = []
        def run(argv, **kwargs):
            calls.append(argv)
            return SimpleNamespace(returncode=returncode, stderr=self.case["messages"][1]["message"])
        namespace.update(
            os=SimpleNamespace(path=SimpleNamespace(expanduser=lambda value: value,
                                                    isfile=lambda value: True), environ={}),
            subprocess=SimpleNamespace(run=run, DEVNULL=-1, PIPE=-1,
                                       TimeoutExpired=subprocess.TimeoutExpired),
            sys=SimpleNamespace(executable="synthetic-python"))
        return namespace, calls

    def test_supported_secrets_are_scrubbed_in_message_and_egress(self):
        namespace, calls = self.alerts()
        for case in self.case["messages"]:
            with self.subTest(case=case["id"]):
                result = namespace["send"]("drift", case["message"], relay="synthetic-relay.py")
                self.assertTrue(result["pushed"])
                self.assertNotIn(case["secret"], result["message"])
                self.assertNotIn(case["secret"], " ".join(calls[-1]))
                self.assertIn("request failed", result["message"])
                self.assertIn("retry later", result["message"])

    def test_egress_failure_and_policy_keep_truthful_results(self):
        namespace, calls = self.alerts(returncode=2)
        result = namespace["send"]("drift", self.case["messages"][0]["message"], relay="synthetic-relay.py")
        self.assertFalse(result["pushed"])
        self.assertNotIn(self.case["messages"][1]["secret"], result["reason"])
        count = len(calls)
        for kwargs in ({"enabled": False}, {"event": "jitter"}):
            options = dict(event="drift", message=self.case["messages"][0]["message"],
                           relay="synthetic-relay.py")
            options.update(kwargs)
            self.assertFalse(namespace["send"](**options)["pushed"])
        self.assertEqual(len(calls), count)

    def test_root_initializer_establishes_canonical_import_path_before_delegation(self):
        path = ROOT / "scripts/init_config.py"
        fake_sys = SimpleNamespace(path=[str(path.parent)])
        delegated = []
        def run_path(target, run_name):
            delegated.append(target)
            spec = importlib.machinery.PathFinder.find_spec("box_binder", fake_sys.path)
            self.assertIsNotNone(spec)
            self.assertEqual(Path(spec.origin), SCRIPTS / "box_binder.py")
            self.assertEqual(Path(target), SCRIPTS / "init_config.py")
            self.assertEqual(run_name, "__main__")
            return {}
        modules = {"os": os, "sys": fake_sys, "runpy": SimpleNamespace(run_path=run_path)}
        original_import = builtins.__import__
        def importing(name, *args, **kwargs):
            return modules[name] if name in modules else original_import(name, *args, **kwargs)
        namespace = {"__name__": "__main__", "__file__": str(path),
                     "__builtins__": dict(vars(builtins), __import__=importing)}
        exec(compile(path.read_bytes(), str(path), "exec"), namespace)
        self.assertEqual(len(delegated), 1)

    def deployment(self):
        namespace = {"json": json,
                     "sha256_text": lambda value: hashlib.sha256(value.encode()).hexdigest()}
        definitions("skills/box-rclone-binder/scripts/boxbinder/drivers.py",
                    {"RemoteError", "HostDriver", "FakeHostDriver"}, namespace)
        namespace.update({"re": re, "shlex": shlex, "posixpath": posixpath,
                          "AUTH_MODES": ("jwt", "ccg-native", "ccg-mint", "oauth-broker")})
        definitions("skills/box-rclone-binder/scripts/boxbinder/config.py",
                    {"ConfigError", "validate_config_dir", "_validate_host_fields", "validate_host"}, namespace)
        remote_namespace = {"json": json, "Path": Path, "SCRIPTS": SCRIPTS,
                            "sha256_text": namespace["sha256_text"]}
        definitions("skills/box-rclone-binder/scripts/boxbinder/remote.py",
                    {"host_settings", "render_secrets_env", "render_health_service",
                     "render_service", "render_health_timer", "_timer", "render_mint_timer",
                     "runtime_manifest", "desired_artifacts", "artifact_fingerprint"},
                    remote_namespace)
        namespace["remote"] = SimpleNamespace(**remote_namespace)
        definitions("skills/box-rclone-binder/scripts/boxbinder/deploy.py",
                    {"_converge_file", "_service_state", "deploy_host"}, namespace)
        return namespace

    def test_role_changes_refuse_before_any_state_mutation(self):
        namespace = self.deployment()
        for old, new in ((self.case["master"], self.case["slave"]),
                         (self.case["slave"], self.case["master"])):
            with self.subTest(prior_role=old["broker_role"]):
                driver = namespace["FakeHostDriver"](old)
                namespace["deploy_host"](driver, old, credentials=self.case["credentials"]
                                          if old["broker_role"] == "master" else None)
                before = copy.deepcopy((driver.fs, driver.services, driver.mutations, driver.exec_log))
                with self.assertRaises(namespace["RemoteError"]) as raised:
                    namespace["deploy_host"](driver, new, credentials=self.case["credentials"])
                self.assertIn("role", str(raised.exception).lower())
                self.assertIn("timer", str(raised.exception).lower())
                self.assertEqual((driver.fs, driver.services, driver.mutations, driver.exec_log), before)

    def test_unreadable_or_invalid_prior_role_state_never_becomes_fresh_deploy(self):
        namespace = self.deployment()
        path = self.case["master"]["config_dir"] + "/host.json"
        for prior in self.case["bad_prior_states"]:
            with self.subTest(prior=prior):
                driver = namespace["FakeHostDriver"](self.case["slave"], fs={path: prior})
                before = copy.deepcopy((driver.fs, driver.services, driver.exec_log))
                with self.assertRaises(namespace["RemoteError"]):
                    namespace["deploy_host"](driver, self.case["slave"])
                self.assertEqual(driver.mutations, 0)
                self.assertEqual((driver.fs, driver.services, driver.exec_log), before)
        driver = namespace["FakeHostDriver"](self.case["slave"])
        def fail_read(target):
            raise namespace["RemoteError"]("read prior state", "synthetic failure")
        driver.read_text = fail_read
        with self.assertRaises(namespace["RemoteError"]):
            namespace["deploy_host"](driver, self.case["slave"])
        self.assertEqual(driver.mutations, 0)

    def test_same_role_and_dry_plan_preserve_existing_contract(self):
        namespace = self.deployment()
        driver = namespace["FakeHostDriver"](self.case["master"])
        namespace["deploy_host"](driver, self.case["master"], credentials=self.case["credentials"])
        repeated = namespace["deploy_host"](driver, self.case["master"])
        self.assertEqual(repeated["status"], "configured")
        self.assertEqual(repeated["mutations"], 0)
        before = copy.deepcopy((driver.fs, driver.services, driver.mutations))
        plan = namespace["deploy_host"](driver, self.case["slave"], dry_run=True)
        self.assertEqual(plan["status"], "planned")
        self.assertEqual((driver.fs, driver.services, driver.mutations), before)

    def atomic(self, case):
        events, notices = [], []
        state = {"temporary_exists": True}
        def action(name):
            events.append(name)
            if case["failure"] == name:
                raise OSError(errno.EIO, "Synthetic I/O failure")
        class File:
            def __enter__(self): return self
            def __exit__(self, *args): action("file_close")
            def write(self, value): action("write")
            def flush(self): action("flush")
            def fileno(self): return 10
        def replace(*args):
            action("replace")
            state["temporary_exists"] = False
        def directory_open(*args):
            action("directory_open")
            return 20
        path = SimpleNamespace(abspath=posixpath.abspath, dirname=posixpath.dirname,
                               exists=lambda value: state["temporary_exists"])
        fake_os = SimpleNamespace(
            name=case["platform"], path=path, O_RDONLY=0,
            makedirs=lambda *args, **kwargs: action("mkdir"),
            fdopen=lambda *args: File(),
            fsync=lambda descriptor: action("file_fsync" if descriptor == 10 else "directory_fsync"),
            chmod=lambda *args: action("chmod"), replace=replace, open=directory_open,
            close=lambda descriptor: action("directory_close"),
            remove=lambda *args: action("remove"))
        namespace = {"os": fake_os, "tempfile": SimpleNamespace(
            mkstemp=lambda **kwargs: (10, "/synthetic/.bbtmp")),
            "assert_same_volume": lambda *args: action("same_volume"),
            "warnings": SimpleNamespace(warn=lambda message, *args, **kwargs: notices.append(message))}
        definitions("skills/box-rclone-binder/scripts/boxbinder/atomic.py", {"atomic_write"}, namespace)
        return namespace, events, notices

    def test_atomic_order_and_failure_contract(self):
        for case in self.case["atomic"]:
            with self.subTest(case=case["id"]):
                namespace, events, notices = self.atomic(case)
                if case["raises"]:
                    with self.assertRaises(OSError) as raised:
                        namespace["atomic_write"]("/synthetic/state.json", self.case["atomic_payload"])
                    self.assertEqual(raised.exception.errno, errno.EIO)
                else:
                    self.assertEqual(namespace["atomic_write"]("/synthetic/state.json",
                                     self.case["atomic_payload"]), "/synthetic/state.json")
                    self.assertLess(events.index("file_fsync"), events.index("replace"))
                    if case["platform"] == "posix":
                        self.assertLess(events.index("replace"), events.index("directory_fsync"))
                        self.assertFalse(notices)
                    else:
                        self.assertNotIn("directory_open", events)
                        self.assertTrue(notices)
                        self.assertIn("durability", notices[0].lower())

    def test_current_entry_docs_do_not_treat_discovery_as_ccg_proof(self):
        for relative, pattern in self.case["docs"]:
            with self.subTest(path=relative, pattern=pattern):
                self.assertIsNone(re.search(pattern, source(relative).decode("utf-8")))
        metadata = json.loads(source(".claude-plugin/plugin.json"))
        self.assertNotRegex(metadata["description"], r"health-check self-heal|cron|Discord alerts")
        self.assertIn("standalone", metadata["description"].lower())
